# 01 Conceptos básicos

* Lista vs Array vs Series

https://github.com/DataJm/data_machine_learning

# Lista

* Se construyen usando los corchetes cuadrados []
* Son ordenadas, mutables y los elementos pueden ser cualquier cosa

Puedes combinar diferentes tipos de datos: strings, enteros, otras listas, etc.



In [2]:
lista = [1,2,3,4,5]

In [3]:
type(lista)

list

# Array

Tambien son colecciones de items

* Son ordenados, mutables, se construyen con algún modulo externo ( usaremos Numpy)
* En general no permite combinar diferentes tipos de datos (pero eso depende del tipo de array)
* Los array son fundamentales en el computo científico, muchos modelos parten de utilizar arrays. 

In [4]:
import numpy as np

In [5]:
array_1 = np.array([1,2,3,4,5])

In [6]:
array_1

array([1, 2, 3, 4, 5])

In [7]:
type(array_1)

numpy.ndarray

In [8]:
array_1 / 2

array([0.5, 1. , 1.5, 2. , 2.5])

# Series

Pandas está construido con Numpy, Python y C. En pandas podemos trabajar con diferentes fuentes de datos: JSON, Excel, SQL, etc. Esta pensado para facilitar operaciones de transformación de datos. 

In [9]:
import pandas as pd

In [10]:
serie = pd.Series([1,2,3,4,5])

In [11]:
type(serie)

pandas.core.series.Series

# En conclusión:

* Mutabilidad: Las 3 estructuras de datos son mutables.
* Homogeneidad: Las listas y las Series son heterogeneas, es decir, puedes tener diferentes tipos de datos. En los Array tenemos el mismo tipo de dato. 
* Accesibilidad: La lista y el array es por posición; en la serie es por index. 
* Las listas son parte de Python 
* El Array está pensando en ser eficiente en el computo estadístico.
* La serie está pensada en el tratamiendo y manipulacíon de datos. 



# Pandas -> Array

In [12]:
dataset = pd.read_csv("./data/01Data.csv")

In [13]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [14]:
dataset.values

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, nan, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', nan, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [15]:
type(dataset.values)

numpy.ndarray

# Métodos de imputación

https://scikit-learn.org/stable/modules/impute.html#impute

# Repaso de objetos en python (clases)

In [20]:
class Persona():
    def __init__(self, name, edad):
        self.name = name
        self.edad = edad
    def saluda(self):
        print(f"Hola amigos, yo soy {self.name}, tengo de edad: {self.edad}")

In [21]:
persona1 = Persona("jose",35)
persona2 = Persona("Marco",30)

In [22]:
persona1.saluda()

Hola amigos, yo soy jose, tengo de edad: 35


In [23]:
persona2.saluda()

Hola amigos, yo soy Marco, tengo de edad: 30


# Regresando a la imputación

In [24]:
from sklearn.impute import SimpleImputer

In [25]:
imputer = SimpleImputer(missing_values = np.nan, strategy="mean")

In [47]:
dataset[["Age","Salary"]]

Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0
3  38.0  61000.0
4  40.0      NaN
5  35.0  58000.0
6   NaN  52000.0
7  48.0  79000.0
8  50.0  83000.0
9  37.0  67000.0

In [49]:
X = dataset.iloc[:,1:-1].values

In [52]:
imputer = imputer.fit(X) # Estoy entrenando mi algoritmo

In [54]:
imputer.transform(X) # Estoy usando mi algoritmo

array([[4.40000000e+01, 7.20000000e+04],
       [2.70000000e+01, 4.80000000e+04],
       [3.00000000e+01, 5.40000000e+04],
       [3.80000000e+01, 6.10000000e+04],
       [4.00000000e+01, 6.37777778e+04],
       [3.50000000e+01, 5.80000000e+04],
       [3.87777778e+01, 5.20000000e+04],
       [4.80000000e+01, 7.90000000e+04],
       [5.00000000e+01, 8.30000000e+04],
       [3.70000000e+01, 6.70000000e+04]])

In [55]:
pd.DataFrame(imputer.transform(X) )

0             1
0  44.000000  72000.000000
1  27.000000  48000.000000
2  30.000000  54000.000000
3  38.000000  61000.000000
4  40.000000  63777.777778
5  35.000000  58000.000000
6  38.777778  52000.000000
7  48.000000  79000.000000
8  50.000000  83000.000000
9  37.000000  67000.000000